### ISSUE TITLE
现在还能用吗？

### ISSUE THREAD

**Issue by WinterChenS** [kernight/jike_gif_reverse_bot#1]
更细之后的即刻API不知道还能不能用

**Comment by kernight** [comment]
刚刚测试了一下，可以正常用。
![2](https://user-images.githubusercontent.com/12738076/54729777-5e55dc00-4bc0-11e9-9e6f-ea2207e1a242.png)
![1](https://user-images.githubusercontent.com/12738076/54729779-6150cc80-4bc0-11e9-992c-9bbc4250ba99.png)
